version: "3.8"

services:

  configserver:
    image: nikhiljose/configserver:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8071:8071"
    networks:
      - eazybank-network

  accounts:
    image: nikhiljose/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: nikhiljose/loans:latest
    ports:
      - "8090:8090"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: nikhiljose/cards:latest
    ports:
      - "9000:9000"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  eazybank-network: